# configs/minatar_rainbow.py

ENV_TYPE = "minatar"

DOUBLE_DQN = True
N_STEP = 3
PRIORITIZED_REPLAY = True

NETWORK_TYPE = "distributional_dueling"
NOISY = True
NUM_ATOMS = 51

ENVIRONMENTS = [
    "MinAtar/Breakout-v1",
]

NUM_FRAMES = 500_000

REPLAY_MEMORY_SIZE = 100_000
REPLAY_MEMORY_INIT_SIZE = 1_000

PER_ALPHA = 0.6
PER_BETA_START = 0.4
PER_BETA_FRAMES = NUM_FRAMES
PER_EPS = 1e-6

DISCOUNT_FACTOR = 0.99
BATCH_SIZE = 32
TARGET_UPDATE_EVERY = 1_000

EPSILON_START = 1.0
EPSILON_END = 0.1
EPSILON_DECAY_STEPS = 200_000

EVAL_EVERY = 50_000
EVAL_LEN = 10_000

RESUME_FROM_CHECKPOINT = False